version: 2.1
jobs:
  test_variables:
    docker:
      -image: cimg/base:stable
    steps:
      - run:
        - name: "Test Practice Variable"
          command: echo $PRACTICE_VARIABLE
workflows:
  test_variables_flow:
    jobs:
      - test_variables:
          context:
            - practice_context
