# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  print-a-message:
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/configuration-reference/#executor-job
    docker:
      - image: cimg/base:2022.03
      # add parameters to the job
    parameters:
      message:
        type: string
    # Add steps to the job
    # See: https://circleci.com/docs/configuration-reference/#steps
    steps:
      - run: echo << parameters.message >>

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  test-workflow:
    jobs:
      - print-a-message:
        message: Hello! Kiran Reddy
