version: 2.1
jobs:
  Test_Variables:
    docker:
      -image: cimg/base:stable
    step:
    	run:
    	  - name: "Test Practice Variable"
    	    command: echo $PRACTICE_VARIABLE
workflows:
  test_variables:
    jobs:
      - Test_Variables
       
